### ISSUE TITLE
Make a draft risk assessment for Rooms and Activity at Wray

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#1]

**Comment by cheapjack** [comment]
Update this once Alastair agrees on use of Marconi/Castle Building Rooms
https://drive.google.com/open?id=1Jqy61kbO2_bnMsMpyGg-k_RwBOj_8h8JsOe3NqhZGyI

**Comment by gkboulter** [comment]
Doc here:
[(https://docs.google.com/spreadsheets/d/1LCy20qvqowFLn_V1JduDk_DZg_tnIHoVPalzMpdenfM/edit?usp=sharing)]
Just need one or two main risks for each activity - add / edit columns if we need more.
