### ISSUE TITLE
Make Signage for event

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#12]
- [ ] RF-Craft Sign
- [ ] Marconi Room Full sign
- [ ] TIffin display
- [x] Confirm any stand-alone FBA signage
- [x] Domestic Science Pull up Poster x 3
- [ ] Signs for each Ok Sparks Table to complement lanyards

Easter Class
- [ ] Make signs for setting up to keep people off limits in Fernery and Buiding room

**Comment by cheapjack** [comment]
- [ ] Signs for @hwayounggit to make each Ok Sparks Table signs to complement lanyards
- [ ] RF-Craft Sign
  
  ## Ross Dalziel
  
  ### RF-Craft
  
  RF-Craft is a simple low power radio messaging system for communicating with Minecraft servers using the Raspberry Pi version of Minecraft and it's accompanying `mcpi` API
  Configurable as Arduino Raspberry Pi HATs make it easy to send analogue and digital messages to and from Minecraft and is meant as a gateway into learning network and wireless communication for non-specialists.
- [ ] Marconi Room sign
  
  ## Furness Amateur Radio Society (FARS)
  
  ### GB2WCR
  
  FARS are a small but active bunch of amateurs and listeners who predominantly live on the Furness peninsula. They are an affiliated club to the RSGB and a member of the Northern Amateur Radio Societies Association.

Today they are running a temporary OFCOM licensed radio station call sign GB2WCR to introduce the public to the world of amateur radio. Please keep numbers in this room to a maximum of 6 people so that everyone can hear the contacts!
- [ ] TIffin display
  ## The Ok Sparks Tiffin Tin

Domestic Science have made a limited edition artwork to allow people to further explore the themes from their artistic research at Wray Castle for Ok Sparks.
- [ ] Derek Hughes
  
  ## Derek Hughes
  
  ### g7lfc.me.uk
  
  Chair of Southport and District Amateur Radio Club
  Derek presents & demos a PSK-data shack- in-a-box and vertical antenna & 2M kit
- [ ] Furness Amateur Radio Society (FARS)
  
  ## Furness Amateur Radio Society (FARS)
  
  ### GB2WCR
  
  FARS are a small but active bunch of amateurs and listeners who predominantly live on the Furness peninsula. They are an affiliated club to the RSGB and a member of the Northern Amateur Radio Societies Association. In the castle building room they will be demo-ing some morse code and other amateur radio kit
- [ ] Pat Langdon
  
  ## Pat Langdon
  
  ### Uplands Rescue Resilience Project
  
  Upland areas contain many “dead” zones that are blind to radio and cellular radio communications. This project explored ways of improving mountain rescue volunteers chances of finding where citizens in danger may be located.

Pat Langdon works at the Cambridge Engineering Design Centre and his experimental and post-doctoral research has contributed to cognitive science, artificial intelligence, robotics and psychophysical studies of the human visual system.
- [ ] Wray Castle Ltd
  ## Karl van Heeswijk
  ### Wray Castle Ltd
  After training at RMS Wray Castle Karl became the lab technician at Wray Castle during it's time teaching marine communication for the Merchant Navy. 

Karl continues to teach radio communication for the contemporary telecoms world at Wray Castle Ltd, the company that emerged from the tenancy at Wray Castle.
- [ ] Dave Mee
  ## Dave Mee

**Comment by hwayounggit** [comment]
[tabletop signs.pdf](https://github.com/cheapjack/oksparks/files/253115/tabletop.signs.pdf)
8 pages

**Comment by hwayounggit** [comment]
[tabletop signs.pdf](https://github.com/cheapjack/oksparks/files/253136/tabletop.signs.pdf)
Please print 2 copies. 8 pages in total.
