### ISSUE TITLE
Make images for press release

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#14]
We need a main image and a domestic science logo asap
- [x] Image
- [x] Domestic Science Logo
- [x] National Trust Logo
- [x] ACE Logo
- [x] FBA Logo
- [ ] Octopus Logo 
- [x] DoESLiverpool Logo

Guidelines
For magazines / papers I normally send 300dpi and 25cm along longest
edge, RGB colour profile.

**Comment by hwayounggit** [comment]
Press image. RBG and CMYK versions at 300 dpi

**Comment by hwayounggit** [comment]
![main-press-cmyk](https://cloud.githubusercontent.com/assets/5999734/13855464/8b04cfd2-ec68-11e5-810d-db9760b73f79.jpg)
![Uploading Main-press-RGB.jpg…]()

**Comment by hwayounggit** [comment]
![main-press-cmyk](https://cloud.githubusercontent.com/assets/5999734/13855485/a1d60366-ec68-11e5-8174-86ef03b0fcee.jpg)
