### ISSUE TITLE
Design the Freshwater Munchkin Game

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#18]
Related to contents of issue #17 

To Fit the 107mm with of tiffin slices see full dimension description in issue #17 
![asterionellatin](https://cloud.githubusercontent.com/assets/128456/14254256/d509b346-fa86-11e5-8739-1a5c9728210d.gif)

**Comment by cheapjack** [comment]
@gkboulter can you give me some introductory text for the board game then I can fit into this [template](https://github.com/cheapjack/oksparks/blob/master/kits/TiffinPaperParts.pdf)?

@cheapjack Some text (two versions)

FULL TEXT:

The Ok Sparks board game is a DIY style game for up to 4 players and a paper counterpart to the Wray Castle Text Adventure. It's also inspired by the way that young children make their own rules up for existing games.

Features:
- Create your own board and race to escape the castle
- Comes with an RPG-style 12 sided die and 4 Algae counters
- The perfect way to pass a rainy afternoon during a Lake District holiday
- Use the blank tiles to write your own rules
- Change the number of laps, board shape and rules to add variation.

Game designed by Glenn Boulter

Warning: Not suitable for young children. 

## Counters may present choking hazard.

SHORT TEXT

The Ok Sparks board game is a DIY style game for up to 4 players

Features:
- Create your own board and race to escape the castle
- Comes with an RPG-style 12 sided die and 4 Algae counters
- The perfect way to pass a rainy afternoon during a Lake District holiday
- Change the objectives, board shape and rules.

Game designed by Glenn Boulter

Warning: Not suitable for young children. 
Counters may present choking hazard.

**Comment by gkboulter** [comment]
Print completed and ordered - arriving early next week for me to cut and package
