### ISSUE TITLE
Write short marketing plan for public event

### ISSUE THREAD

**Issue by gkboulter** [cheapjack/oksparks#2]

**Comment by cheapjack** [comment]
added to list below

**Comment by gkboulter** [comment]
- [x] Contact Rhonda Webster - Marketing @ NT - Rona Webster Rona.Webster@nationaltrust.org.uk
- [x] Check on logos to be included on publicity (ACE / NT / other)
- [x] Contact Westmoreland Gazzette with press release for pubic events (April)

**Comment by cheapjack** [comment]
Ok so far we are going to:
- [ ] Do an article with Westmoreland Gazette
- [ ] Do an article/post with Cumbria Life
- [ ] Do an article/ad with Cumbria Tourism
