### ISSUE TITLE
Design all the print for OK Sparks!

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#20]
We need to include
- [x] Freshwater Munchkin game (Glenn)
- [x] Notebooks for Easter Class participants (Glenn)
- [ ] Tiffin tin content (Ross)
- [x] Signage #12 (Ross)
- [x] A5 pamphlet (Hwa Young)
- [x] Postcards (Hwa Young)
- [x] [Pull up Banners](https://www.rollerbannersuk.com/budget-roller-banners/)

**Comment by cheapjack** [comment]
Postcards could be done this week so we can start distributing them based on the press release image

**Comment by cheapjack** [comment]
### A5 Pamphlet 8pg

Cover
1  Introduction & History 
2 & 3 Text Adventure & Boardgame (Glenn)
4 & 5 FBA (Hwa Young)
6 & 7 Wray Radio Cultures (Ross)
8 Domestic Science
Cover with Logos

**Comment by cheapjack** [comment]
### A6 Postcard

2 side image/artwork
Rear Logos / info

**Comment by cheapjack** [comment]
## A5 Notebooks for the Easter Class

2 spreads of graph paper with a thicker coloured paper stock cover like for Text Adventure Time

**Comment by gkboulter** [comment]
Link to text and image(s) for A5 Brochure from Glenn:
[Text](https://drive.google.com/drive/folders/0B18v6qTGYbxYa29sek5yaTh2NTg)

**Comment by cheapjack** [comment]
## Roller Banners 800mm x 2100mm

[Template](https://cdn.shopify.com/s/files/1/0069/4012/files/Budget_Roller_Banner_Templates.pdf?1554)

## BANNER 1

_Main image circles_

### Ok Sparks!

Artists **Hwa Young Jung**, **Ross Dalziel** and **Glenn Boulter** from **Domestic Science** present two weekends of activity, workshops and pervasive games exploring Wray Castle.

They invited scientists and local radio experts to help visitors explore freshwater biology, reflect on contemporary radio cultures, play mobile Text Adventure games and a Minecraft radio treasure hunt to investigate the hidden histories and tenants of a very special place in the Lake District with a unique role in the history of science and communication.

slyrabbit.net/ok-sparks
#oksparks
@ok_sparks

### Domestic Science

**Domestic Science** explore the narratives around the science and data that surrounds us everyday. Behind every model we build to understand the world, there is a story. In turn every model influences the stories we tell ourselves about the world.

domesticscience.org.uk
@DomesticaSci

Ok Sparks! is the first major project for the collective 

### What's on

### Ok Sparks Radio Day 1

**CQ CQ this is GB2WCR calling CQ...
Saturday 7th May 2016
Castle Building Room & Marconi Room
10:30 - 16:30
Drop in / Free with General Admission
All Ages**

### Ok Sparks! Day 2

**Sunday 8th May 2016
Castle Building Room & Marconi Room
10:30 - 16:30
Drop in / Free with General Admission
All Ages**

### Minecraft Radio Treasure Hunt

**Saturday 7th & Sunday 8th May 2016
12:30, 14:30, 1530
Castle Building Room, Wray Castle
Drop in / Free with General Admission
All Ages**

### The Wray Castle Text Adventure

**Saturday 7th, Sunday 8th, Saturday 14th & Saturday 15th May 2016
10:30 - 16:30
Castle Building Room & Morning Room, Wray Castle
Drop in / Free with General Admission
All Ages**

### The Easter Class

**Saturday 14th & Sunday 15th May 2016
13:30 - 16.30
The Fernery, Wray Castle
Bookable at http://slyrabbit.net/fba-easter-class/ or at the front desk - £4.50 plus General Admission
Ages 14 and up, limited tickets**

### The Easter Class Reading Room

**Saturday 14th & Sunday 15th May 2016
13:30 - 16.30
The Morning Room, Wray Castle
Drop in FREE with General Admission
All Ages**

--logos--

## BANNER 2 EVENT 1

_Main image circles_

### Ok Sparks Radio Day 1

**CQ CQ this is GB2WCR calling CQ...
Saturday 7th May 2016
Castle Building Room & Marconi Room
10:30 - 16:30
Drop in / Free with General Admission**

Free activity reflecting on the past of the Merchant Navy at Wray Castle with Furness Amateur Radio Society (FARS) an active community who recently celebrated 100 years of Amateur Radio in Furness in 2013. Barrow Wireless Association was one of the first amateur radio clubs to be issued with a transmitting licence in the UK, on the 26th June 1913. 

Experience a special temporary OFCOM licensed Wray Castle Radio station, GB2WCR, send radio messages to Minecraft, play with simple messaging equipment and learn about the continued importance of radio culture.

### Ok Sparks! Day 2

*_Sunday 8th May 2016
Castle Building Room & Marconi Room
10:30 - 16:30
Drop in / Free with General Admission
*_
Continue to explore DIY radio culture with special guests and the Minecraft Radio Treasure Hunt.

### Minecraft Radio Treasure Hunt

**Saturday 7th & Sunday 8th May 2016
12:30, 14:30, 1530
Castle Building Room, Wray Castle
Drop in / Free with General Admission**

Special Minecraft blocks have been hidden around the castle: when you find them low power radio modules send a message to a local Minecraft server and reveal hidden treasure and information about Wray Castle’s past

### The Wray Castle Text Adventure

**Saturday 7th, Sunday 8th May 2016
10:30 - 16:30
Castle Building Room, Wray Castle
Drop in / Free with General Admission**

The Wray Castle Text Adventure is a playful interactive story encouraging young people to explore the castle’s unique architecture and learn about some of its former inhabitants. 

--logos--

## BANNER 3 EVENT 2

_Main image circles_

### The Easter Class

**Saturday 14th & Sunday 15th May 2016
13:30 - 16.30
The Fernery, Wray Castle
Bookable at http://slyrabbit.net/fba-easter-class/ or at the front desk - £4.50 plus General Admission
Ages 14 and up, limited tickets**

Investigate the ecology of the Lakes with hands-on activities about chemistry, algae, fish, invertebrates and more on this ticketed event.

### The Easter Class Reading Room

**Saturday 14th & Sunday 15th May 2016
13:30 - 16.30
The Morning Room, Wray Castle
Drop in FREE with General Admission
All Ages**

Discover the role the **Freshwater Biological Association** have had on local and international science with FBA volunteers and browse a temporary Reading Room of fascinating illustrated publications on Freshwater science.

### The Wray Castle Text Adventure

**Saturday 14th,  & Sunday 15th May 2016
10:30 - 16:30
The Morning Room, Wray Castle
Drop-in / Free with General Admission**

The Wray Castle Text Adventure is a playful interactive story encouraging young people to explore the castle’s unique architecture and learn about some of its former inhabitants. 

--logos--

**Comment by hwayounggit** [comment]
Draft of the 8pg pamphlet. Cover is A4 landscape - black only. Will print on green paper. To be staple bound.
[brochure A5.pdf](https://github.com/cheapjack/oksparks/files/227783/brochure.A5.pdf)
[brochure cover A4.pdf](https://github.com/cheapjack/oksparks/files/227784/brochure.cover.A4.pdf)

**Comment by hwayounggit** [comment]
Final draft. Please look over typo, consistency, etc etc. Aim to send to print by 26th May.
[brochure A5 FINAL.pdf](https://github.com/cheapjack/oksparks/files/229722/brochure.A5.FINAL.pdf)

**Comment by cheapjack** [comment]
1. Comments/amends 
2. Page 2 1st Para "operatingthemed puzzles" needs space
3. Page 2 2nd Para "Teletextstyle" needs space
4. Page 2 4th Para "in a way that is arguably more effectively." change to "effective."
5. Page 2 Change italiscised text:
   _The Wray Castle Text Adventure runs on the weekends of 7th,8th, 14th and 15th May between 10:30 and 16:30. Visitors can find us in the Morning room or Castle Building Room to download the game locally to their mobile device or borrow a tablet. Also available from the **domesticscience.org.uk** website_
6. Page 3 3rd Para "asa analysis" to "as an analysis"  
7. Page 3 Final italicised text change the easter class bitly link to human readable link (ive made a new one and included a fwd to the Sunday class from the Saturday eventbrite page)
   "_http://bit.ly/easterclass_"
   It's brilliantly designed thank you!
   http://bit.ly/easterclass
8.

**Comment by hwayounggit** [comment]
[brochure A5 FINAL.pdf](https://github.com/cheapjack/oksparks/files/236301/brochure.A5.FINAL.pdf)

Have updated the comments/ amends and ran it through spell check. Found a few others.

**Comment by cheapjack** [comment]
Final amends

Ok pamphlet looks good to go for me; but I think you may want your subtitle to be (page 4) 

Pamphlet Amend: (page 4)
"Searching for the freshwater prince of Blelham Tarn”
( as Beltarn unlike Bel Air doesn’t exist)
Im afraid there’s 2 errors in banners to do with location of the text adventure, my fault not yours:

Banner 1 amend:

The Wray Castle Text Adventure

Saturday 7th, Sunday 8th, Saturday 14th & Saturday 15th May  10:30 - 16:30
8th & 9th; Castle Building Room, 14th & 15th May; Morning Room 
Drop in | Free with General Admission | All Ages

Banner 3 amend

The Wray Castle Text Adventure

Saturday 14th & Saturday 15th May 10:30 - 16:30 
Castle Building Room
Drop in | Free with General Admission | All Ages

The Wray Castle Text Adventure is a playful interactive story encouraging young people to explore the castle’s unique architecture and learn about some of its former inhabitants.

**Comment by cheapjack** [comment]
Main Signage #12 delivered no just home printed paper signs left
