### ISSUE TITLE
Complete Marketing Tasks

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#23]
- [x] Contact Rona to post on National Trust site like [this](http://www.nationaltrust.org.uk/events/daf6e590-59df-4efc-8c71-1eb83bac974b/pages/details)
- [x] Westmoreland Gazette
- [ ] [Lakes Culture](http://lakesculture.co.uk/)
- [ ] [Cumbria Live](http://www.cumbrialive.co.uk/)

**Comment by cheapjack** [comment]
Tell [Museum of Water](http://www.museumofwater.co.uk/) people what we are doing, they might like to join the Easter Class as fellow water geeks!

**Comment by gkboulter** [comment]
Sent PR and images to Rona 12/4/16
