### ISSUE TITLE
Pi & pico for Glenn's projection

### ISSUE THREAD

**Issue by cheapjack** [cheapjack/oksparks#35]

**Comment by cheapjack** [comment]
IM at ODI Leeds on Saturday, Ben could give me the projector then?

**Comment by gkboulter** [comment]
Arriving tomorrow by post from Dave Lynch.

**Comment by cheapjack** [comment]
@gkboulter will provide `mp4` of video loop for pico , @cheapjack will provide pi & looper image Can be silent of with intermittent groans

**Comment by gkboulter** [comment]
Dave has sent pi with projector from Labs box.

**Comment by cheapjack** [comment]
I still love the idea of realising this maybe Pico project on the domestic science stand at Liverpool Makefest
